version: '3'

services:
  php:
    build: 
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - /home/ec2-user/html:/app
  web:
    build:
      dockerfile: nginx.Dockerfile
      context: .
    restart: always
    volumes:
      - /home/ec2-user/html:/app
    depends_on:
      - php
    ports:
      - "80:80"
    stdin_open: true
  composer_installation:
    image: composer:latest
    volumes:
    - /home/ec2-user/html:/app
    command: composer install --ignore-platform-reqs